---
title: "Plot FRiP scores"
author: "Tyler Hansen"
date: "6/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, Libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(extrafont)
loadfonts(device = "win")
```

```{r, Compare FRiP scores}
#Using the FRIP scores results, make a dataframe for ggploting

results <- data.frame(frip = c(63311006,26736172), total = c(90504726,129433258), sample = c("ATAC-STARR", "Buenrostro")) %>% mutate(frip_perc = frip/total)

frip <- ggplot(results, aes(x=sample, y=frip_perc)) +
  geom_col(aes(fill=sample), color = "black") +
  scale_fill_manual(values = c("steelblue", "forestgreen")) +
  coord_cartesian(ylim=c(0,1)) +
  ylab("Fraction of PE fragments in Peaks") +
  theme_bw(base_size = 6, base_family = "Arial") +
  theme(legend.position = "none",  
        axis.title.x = element_blank(), axis.text = element_text(angle = 90))

#ggsave(frip, filename = "C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/accessibility/ATAC-STARR_vs_Buenrostro/frip-scores.pdf", device = cairo_pdf, width = 1.25, height = 2)
```