---
title: "Annotation by Genomic Position to TSS"
author: "Tyler Hansen"
date: "April 29th, 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, Libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(ChIPseeker)
library(extrafont)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
loadfonts(device = "win")
```


```{r}
active <- annotatePeak("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/data/activity/individual/DESeq2_results/bin-method/GM12878inGM12878_active_0.1padj_50-bin.merged.bed", tssRegion = c(-2000, 1000), TxDb = TxDb.Hsapiens.UCSC.hg38.knownGene, annoDb = "org.Hs.eg.db", flankDistance = 5000)

silent <- annotatePeak("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/data/activity/individual/DESeq2_results/bin-method/GM12878inGM12878_silent_0.1padj_50-bin.merged.bed", tssRegion = c(-2000, 1000), TxDb = TxDb.Hsapiens.UCSC.hg38.knownGene, annoDb = "org.Hs.eg.db", flankDistance = 5000)

ocr <- annotatePeak("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/data/accessibility/genrich_ATAC-like_peaks/GM12878inGM12878_DNA_genrich_0.0001-qvalue.narrowPeak", tssRegion = c(-2000, 1000), TxDb = TxDb.Hsapiens.UCSC.hg38.knownGene, annoDb = "org.Hs.eg.db", flankDistance = 5000)

bar <- plotAnnoBar(list(`OCRs`=ocr, `Active Peaks`=active, `Silent Peaks`=silent)) + theme_bw(base_size = 8, base_family = "Arial") + theme(legend.key.size = unit(0.1, "in"), legend.title = element_blank(), plot.title = element_blank(), legend.position = "top", legend.text = element_text(size = 6)) 

ggsave("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/activity/ATAC-STARR_RE_analysis/GM12878_annotation-barchart.pdf", plot = bar, device = cairo_pdf, width = 4, height = 2)
```

