---
title: "ATAC-STARR Accessibility Peaks vs Buenrostro ATAC-seq Peaks"
author: "Tyler Hansen"
date: "4/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
```

```{r, Libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(extrafont)
loadfonts(device = "win")
library(eulerr)
```

```{r, Euler Plot, message=FALSE}
#### View Region Overlap as a Venn Diagram ####
#These numbers are from doing a bedtools jaccard on accre:
# [hansetj1@gw344 genrich_ATAC-like_peaks]$ bedtools jaccard -a GM12878inGM12878_DNA_genrich_0.0001-qvalue.narrowPeak -b /data/hodges_lab/public_data/GM12878/obtained_as_raw_files/ATAC_GM12878_2013-buenrostro/data/genrich_peaks/GM12878_ATAC-seq_buenrostro_genrich_0.0001-qvalue.narrowPeak
# intersection    union   jaccard n_intersections
# 33425827        67388153        0.496019        51923
# [hansetj1@gw344 genrich_ATAC-like_peaks]$ wc -l GM12878inGM12878_DNA_genrich_0.0001-qvalue.narrowPeak
# 69563 GM12878inGM12878_DNA_genrich_0.0001-qvalue.narrowPeak
# [hansetj1@gw344 genrich_ATAC-like_peaks]$ wc -l /data/hodges_lab/public_data/GM12878/obtained_as_raw_files/ATAC_GM12878_2013-buenrostro/data/genrich_peaks/GM12878_ATAC-seq_buenrostro_genrich_0.0001-qvalue.narrowPeak
# 82337 /data/hodges_lab/public_data/GM12878/obtained_as_raw_files/ATAC_GM12878_2013-buenrostro/data/genrich_peaks/GM12878_ATAC-seq_buenrostro_genrich_0.0001-qvalue.narrowPeak

#Make a vector of the values above:
combo <- c(`Buenrostro et al. 2013\nATAC-seq Peaks` = 82337-51923, `ATAC-STARR\nAccessibility Peaks` = 69563-51923, "Buenrostro et al. 2013\nATAC-seq Peaks&ATAC-STARR\nAccessibility Peaks" = 51923)
eul <- plot(euler(combo), quantities = TRUE) 

eul

#ggsave(eul, filename = "C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/accessibility/ATAC-STARR_vs_Buenrostro/euler-plot.pdf", device = cairo_pdf, width = 5, height = 3)
```
