---
title: "Plot Motif Enrichment Results"
author: "Tyler Hansen"
date: "6/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, Libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(extrafont)
loadfonts(device = "win")
library(egg)
library(data.table)
library(ggrepel)
```

```{r, Compare Motif Enrichment Results}
#### Compare TF Motif Enrichment ####
#Read in motif results txt files with this function. 
format_motif_results <- function(df){
  df <- mutate(df, percentTargetNum = (as.numeric(gsub("%", "", percentTarget, fixed = TRUE))/100))
  df <- mutate(df, percentBackgroundNum = (as.numeric(gsub("%", "", percentBackground, fixed = TRUE))/100)) 
  df <- mutate(df, percentFold = (percentTargetNum/percentBackgroundNum))
  df <- mutate(df, Motif = gsub("\\(.*", "", MotifName))
  df$Motif <- factor(df$Motif,levels=rev(unique(df$Motif)))
  # Plot with GGPlot
  return(df)
}

AS <- read_tsv("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/accessibility/Motif_Analysis/GM12878inGM12878_DNA_genrich_0.0001-qvalue/knownResults.txt", col_names=c("MotifName","Consensus","p","logp","q","numTarget", "percentTarget","numBackground","percentBackground"), skip = 1)

buen <- read_tsv("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/accessibility/Motif_Analysis/GM12878_ATAC-seq_buenrostro_genrich_0.0001-qvalue/knownResults.txt", col_names=c("MotifName","Consensus","p","logp","q","numTarget", "percentTarget","numBackground","percentBackground"), skip = 1)

AS <- format_motif_results(df=AS) 
AS_text <- filter(AS, rank(logp) <= 15 | rank(dplyr::desc(percentFold)) >= 15)
buen <- format_motif_results(df=buen) 
buen_text <- filter(buen, rank((logp)) <= 15 | rank(dplyr::desc(percentFold)) <= 15)

p_AS <- ggplot(AS, aes(x=abs(as.numeric(logp)), y=percentFold)) + 
    geom_point(color="steelblue", size = 0.5) +
    geom_text_repel(data=AS_text, aes(x=abs(as.numeric(logp)), y=percentFold, label = Motif), 
               hjust = 0.5, nudge_y = 0.3, size = 2, fontface = "italic", 
               max.overlaps = getOption("ggrepel.max.overlaps", default = 15)) + 
    ggtitle("ATAC-STARR Peaks") +
    labs(x = bquote("-"~log[10]~"(p-value)"), y = "fold-change enrichment") +
    theme_bw(base_size = 8, base_family = "Arial") +
    theme(plot.title = element_text(hjust = 0.5, size = 8, face = "bold"))

p_buen <- ggplot(buen, aes(x=abs(as.numeric(logp)), y=percentFold)) + 
    geom_point(color="forestgreen", size = 0.5) +
    geom_text_repel(data=buen_text, aes(x=abs(as.numeric(logp)), y=percentFold, label = Motif), 
               hjust = 0.5, nudge_y = 0.3, size = 2, fontface = "italic", 
               max.overlaps = getOption("ggrepel.max.overlaps", default = 15)) + 
    ggtitle("Buenrostro Peaks") +
    labs(x = bquote("-"~log[10]~"(p-value)"), y = "fold-change enrichment") +
    theme_bw(base_size = 8, base_family = "Arial") +
    theme(plot.title = element_text(hjust = 0.5, size =8, face = "bold"))

p <- ggarrange(p_AS, p_buen, nrow = 2)

p 

#ggsave("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/accessibility/ATAC-STARR_vs_Buenrostro/Motif-Results.pdf", p, device = cairo_pdf, width = 2.5, height = 4)
```