---
title: "NAR Paper - Supp 3"
author: "Tyler Hansen"
date: "5/19/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(extrafont)
loadfonts(device = "win")
library(ggforce)
library(eulerr)
```

```{r}
df <- data.frame(
  method = factor(x = c("Fragment Groups\n(FDR < 0.1)", "Sliding Windows\n(FDR < 0.1)"), levels = c("Fragment Groups\n(FDR < 0.1)", "Sliding Windows\n(FDR < 0.1)")),
  regions = c(10203, 14617)
)

p <- ggplot(df, aes(x=method, y=regions)) + 
  geom_col(aes(fill=method)) +
  geom_text(aes(label=regions), position=position_dodge(width=0.9), vjust=-0.25, size = 2) +
  scale_fill_manual(values = c("navy", "orange")) +
  theme_light(base_size = 6, base_family = "Arial") +
  theme(legend.position = "none", axis.title.x = element_blank(), axis.text.x = element_text(hjust = 0.5)) +
  ylab("# Active Regions Called")

ggsave(plot = p, filename = "C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/activity/Supp_3/region_count.pdf", device = cairo_pdf, width = 3, height = 3)
```

```{r, Euler Plot, message=FALSE}
#### View Region Overlap as a Venn Diagram ####

#Make a vector of the values above:
combo <- c(`Fragment Groups` = 10203-8220, `Sliding Windows` = 14617-8220, "Fragment Groups&Sliding Windows" = 8220)
eul <- plot(euler(combo), quantities = TRUE) 

eul

ggsave(eul, filename = "C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/activity/Supp_3/euler-plot.pdf", device = cairo_pdf, width = 5, height = 3)
```

```{r}
df <- data.frame(
  duplicates = factor(x = c("included", "removed", "included", "removed"), levels = c("included", "removed")),
  Region = factor(x = c("active", "active", "silent", "silent"), levels = c("active", "silent")),
  count = c(14617, 3855, 19393, 11757)
)

p <- ggplot(df, aes(x=duplicates, y=count)) + 
  geom_col(aes(fill=Region), position = "dodge2") +
  geom_text(aes(label=count), position=position_dodge2(width=0.9), vjust=-0.25, size = 2) +
  scale_fill_manual(values = c("Steelblue", "Firebrick")) +
  theme_bw(base_size = 6, base_family = "Arial") +
  theme(legend.position = c(0.75,0.9), axis.title.x = element_blank(), axis.text.x = element_text(hjust = 0.5), legend.key.size = unit(0.1, units = "in"), legend.background = element_rect(fill="white", color = "black")) +
  ylab("# regions Called")

ggsave(plot = p, filename = "C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/activity/Supp_3/plus-minus-duplicates_regions-counts.pdf", device = cairo_pdf, width = 1.5, height = 3)
```


