---
title: "Plotting Motif Enrichment Results from HOMER - ATAC-STARR"
author: "Tyler Hansen"
date: "February 15th, 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Software, message=FALSE, warning=FALSE}
library(tidyverse)
library(extrafont)
loadfonts(device="win")
library(egg)
library(ggrepel)
```

```{r, Plot GM12878inGM12878 Active, message=FALSE}
format_motif_results <- function(df){
  df <- mutate(df, percentTargetNum = (as.numeric(gsub("%", "", percentTarget, fixed = TRUE))/100))
  df <- mutate(df, percentBackgroundNum = (as.numeric(gsub("%", "", percentBackground, fixed = TRUE))/100)) 
  df <- mutate(df, percentFold = (percentTargetNum/percentBackgroundNum))
  df <- mutate(df, Motif = gsub("\\(.*", "", MotifName))
  df <- dplyr::filter(df, percentFold != "Inf")
  df$Motif <- factor(df$Motif,levels=rev(unique(df$Motif)))
  # Plot with GGPlot
  return(df)
}

#Read in motif results txt files
setwd("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/activity/Motif_Analysis/")

active <- read_tsv("GM12878inGM12878_active_0.1padj_50-bin.merged/knownResults.txt", col_names=c("MotifName","Consensus","p","logp","q","numTarget", "percentTarget","numBackground","percentBackground"), skip = 1)

active_res <- format_motif_results(df=active)
active_res_text <- dplyr::filter(active_res, rank(logp) <= 20 | rank(dplyr::desc(percentFold)) <= 20)

active <- ggplot(active_res, aes(x=abs(as.numeric(logp)), y=percentFold)) + 
    geom_point(color="steelblue", size = 0.5) +
    geom_text_repel(data=active_res_text, aes(x=abs(as.numeric(logp)), y=percentFold, label = Motif), 
               hjust = 0.5, nudge_y = 0.3, size = 2, fontface = "italic", 
               max.overlaps = getOption("ggrepel.max.overlaps", default = 15)) + 
    ggtitle("Active Peaks") +
    labs(x = bquote("-"~log[10]~"(p-value)"), y = "fold-change enrichment") +
    theme_bw(base_size = 8, base_family = "Arial") +
    theme(plot.title = element_text(hjust = 0.5, size = 8, face = "bold"))

ggsave("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/activity/Motif_Analysis/GM12878inGM12878_active_Motif-Results.pdf", active, device = cairo_pdf, width = 2.5, height = 3)
```

```{r, Plot GM12878inGM12878 Silent, message=FALSE}
format_motif_results <- function(df){
  df <- mutate(df, percentTargetNum = (as.numeric(gsub("%", "", percentTarget, fixed = TRUE))/100))
  df <- mutate(df, percentBackgroundNum = (as.numeric(gsub("%", "", percentBackground, fixed = TRUE))/100)) 
  df <- mutate(df, percentFold = (percentTargetNum/percentBackgroundNum))
  df <- mutate(df, Motif = gsub("\\(.*", "", MotifName))
  df <- dplyr::filter(df, percentFold != "Inf")
  df$Motif <- factor(df$Motif,levels=rev(unique(df$Motif)))
  # Plot with GGPlot
  return(df)
}

#Read in motif results txt files
setwd("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/activity/Motif_Analysis/")

silent <- read_tsv("GM12878inGM12878_silent_0.1padj_50-bin.merged/knownResults.txt", col_names=c("MotifName","Consensus","p","logp","q","numTarget", "percentTarget","numBackground","percentBackground"), skip = 1)

silent_res <- format_motif_results(df=silent)
silent_res_text <- dplyr::filter(silent_res, rank(logp) <= 15 | rank(dplyr::desc(percentFold)) <= 15)

silent <- ggplot(silent_res, aes(x=abs(as.numeric(logp)), y=percentFold)) + 
    geom_point(color="firebrick", size = 0.5) +
    geom_text_repel(data=silent_res_text, aes(x=abs(as.numeric(logp)), y=percentFold, label = Motif), 
               hjust = 0.5, nudge_y = 0.3, size = 2, fontface = "italic", 
               max.overlaps = getOption("ggrepel.max.overlaps", default = 15)) + 
    ggtitle("Silent Peaks") +
    labs(x = bquote("-"~log[10]~"(p-value)"), y = "fold-change enrichment") +
    theme_bw(base_size = 8, base_family = "Arial") +
    theme(plot.title = element_text(hjust = 0.5, size = 8, face = "bold"))

ggsave("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/activity/Motif_Analysis/GM12878inGM12878_silent_Motif-Results.pdf", silent, device = cairo_pdf, width = 2.5, height = 3)
```