---
title: "ATAC-STARR RE Size Distribution"
author: "Tyler Hansen"
date: "5/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(extrafont)
loadfonts(device = "win")

active <- read_tsv("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/data/activity/individual/DESeq2_results/bin-method/GM12878inGM12878_active_0.1padj_50-bin.merged.bed", col_names = c("Chr", "Start", "End", "Name", "Score", "Strand")) %>% mutate(length = End-Start, Type = "active")
silent <- read_tsv("C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/data/activity/individual/DESeq2_results/bin-method/GM12878inGM12878_silent_0.1padj_50-bin.merged.bed", col_names = c("Chr", "Start", "End", "Name", "Score", "Strand")) %>% mutate(length = End-Start, Type = "Silent")

all <- bind_rows(active, silent)

p <- ggplot(all, aes(x=length, fill = Type)) +
  geom_density(color = "black", alpha = 0.5) +
  theme_bw(base_size = 8, base_family = "Arial") + 
  ggtitle("ATAC-STARR Regulatory Element Size Distribution") +
  coord_cartesian(xlim = c(50,800)) +
  scale_fill_manual(values = c("steelblue","firebrick")) +
  scale_x_continuous(breaks = seq(from = 50, to = 800, by =100)) +
  theme(legend.position = "bottom", plot.title = element_text(face="bold"), legend.title = element_blank())

p

ggsave(p, filename = "C:/Users/tyler/Dropbox (VU Basic Sciences)/Hodges Lab/Results and Data/Bioinformatics/ATAC-STARR_analysis/3_Accre_Local/ATAC-STARR/results/activity/ATAC-STARR_RE_analysis/size_distribution.pdf", device = cairo_pdf, height = 3, width = 3) 
```

